# This workflow will run tests using node on master branch pull requests

name: Node.js Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - working-directory: ./src
        run: npm ci
      - working-directory: ./src
        run: npm test
