# This workflow will run tests using node and then publish a package to npmjs.com when a v* tag is created

name: Node.js Package

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Vérifie que le tag correspond à la version du package
        run: |
          TAG_VERSION=${GITHUB_REF##*/}
          PACKAGE_VERSION="v"$(node -p "require('./src/package.json').version")
          echo "Tag: $TAG_VERSION"
          echo "Package.json version: $PACKAGE_VERSION"
          if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "::error::Le tag '$TAG_VERSION' ne correspond pas à la version du package '$PACKAGE_VERSION'"
            exit 1
          fi
      - working-directory: ./src
        run: npm test

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
      - working-directory: ./src
        run: npm ci
      - working-directory: ./src
        run: npm run build
      - working-directory: ./src
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
